services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sreehari
      MONGO_INITDB_ROOT_PASSWORD: 2021Endgame

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  customers:
    build: ./services/customers
    container_name: customers
    environment:
      MONGO_URI: mongodb://sreehari:2021Endgame@mongo:27017/customers?authSource=admin
      KAFKA_BROKER: kafka:9092
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - kafka

  products:
    build: ./services/products
    container_name: products
    environment:
      MONGO_URI: mongodb://sreehari:2021Endgame@mongo:27017/products?authSource=admin
      KAFKA_BROKER: kafka:9092
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - kafka

  orders:
    build: ./services/orders
    container_name: orders
    environment:
      MONGO_URI: mongodb://sreehari:2021Endgame@mongo:27017/orders?authSource=admin
      KAFKA_BROKER: kafka:9092
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - kafka
