name: CI/CD Microservices
on:
  push:
    paths:
      - 'services/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [customers, products, orders]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myrepo/${{ matrix.service }} ./services/${{ matrix.service }}

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push myrepo/${{ matrix.service }}:latest
